name: CI

on:
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - 'custom-game-area/**'
  push:
    branches:
      - development
    tags:
      - 'v*'
    paths-ignore:
      - '.idea/**'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - 'renovate.json'
      - 'custom-game-area/**'
      - 'FUNDING.yml'
  workflow_dispatch:
    inputs:
      release-canary:
        description: 'Release canary or not'
        default: 'true'
        required: true
env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/development' || inputs.release-canary != 'false'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Determine Version Name
        shell: bash
        run: |
          VERSION_CODE=${{ github.run_number }}
          VERSION_NAME=${{ github.run_number }}

          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            VERSION_NAME = ${{ github.ref_name }}
          fi
          echo "FGA_VERSION_CODE=$VERSION_CODE" >>${GITHUB_ENV}
          echo "FGA_VERSION_NAME=$VERSION_NAME" >>${GITHUB_ENV}

      - name: Build Android Package
        run: ./gradlew assemblepreview --scan --parallel --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/preview/app-preview.apk

      - name: Upload De-obfuscation mapping file
        uses: actions/upload-artifact@v4
        with:
          name: mapping-preview
          path: app/build/outputs/mapping/preview/mapping.txt

  # Release master branch
  canary:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apk

      - name: Rename apk
        run: mv app-preview.apk io.github.fate_grand_automata-preview.apk

      - id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "canary"
          prerelease: true
          title: 'FGA canary-${{ github.run_number }}'
          files: |
            *.apk
