name: CI

on:
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - 'custom-game-area/**'
  push:
    branches:
      - development
    tags:
      - 'v*'
    paths-ignore:
      - '.idea/**'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - 'renovate.json'
      - 'custom-game-area/**'
      - 'FUNDING.yml'
  workflow_dispatch:
    inputs:
      release-canary:
        description: 'Release canary or not'
        default: 'true'
        required: true
env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'

jobs:
  build:
    runs-on: macos-latest
    if: github.ref != 'refs/heads/development' || inputs.release-canary != 'false'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: pip install httpx

      - name: Determine development branch or pull request
        run: |
          if [[ ${{ github.ref }} == refs/heads/development ]]; then
            echo "BRANCH=development" >>${GITHUB_ENV}
          else
            echo "BRANCH=${{ github.head_ref }}" >>${GITHUB_ENV}
          fi

      - name: Determine Pull Request Number
        run: |
          if [[ ${{ github.ref }} == refs/heads/development ]]; then
            echo "PR_NUMBER=0" >>${GITHUB_ENV}
          else
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >>${GITHUB_ENV}
          fi
      - name: Determine the repository name and owner
        run: |
          echo "REPO_NAME=${{ github.repository }}" >>${GITHUB_ENV}

      - name: save the Github secrets
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >>${GITHUB_ENV}

      - name: Run Python Create Release notes
        run: python .github/scripts/create_release_notes.py

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Determine Version Name
        shell: bash
        run: |
          VERSION_CODE=${{ github.run_number }}
          VERSION_NAME=${{ github.run_number }}

          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            VERSION_NAME = ${{ github.ref_name }}
          fi
          echo "FGA_VERSION_CODE=$VERSION_CODE" >>${GITHUB_ENV}
          echo "FGA_VERSION_NAME=$VERSION_NAME" >>${GITHUB_ENV}

      - name: Build Android Package
        run: |
          if [[ ${{ github.ref }} == refs/heads/development ]]; then
            ./gradlew assemblepreview --scan --parallel --no-daemon
          else
            ./gradlew assembleCi --scan --parallel --no-daemon
          fi

      - name: Rename APK
        run: |
          if [[ ${{ github.ref }} == refs/heads/development ]]; then
            echo "FGA_PATH=app/build/outputs/apk/preview/app-preview.apk" >>${GITHUB_ENV}
            echo "FGA_MAPPING_PATH=app/build/outputs/mapping/preview/mapping.txt" >>${GITHUB_ENV}
          else
            mv app/build/outputs/apk/ci/app-ci.apk app/build/outputs/apk/ci/fga-pr-${{ github.event.pull_request.number }}-build-${{ github.run_number }}.apk
            echo "FGA_PATH=app/build/outputs/apk/ci/fga-pr-${{ github.event.pull_request.number }}-build-${{ github.run_number }}.apk" >>${GITHUB_ENV}
            echo "FGA_MAPPING_PATH=app/build/outputs/mapping/ci/mapping.txt" >>${GITHUB_ENV}
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ env.FGA_PATH }}

      - name: Upload De-obfuscation mapping file
        uses: actions/upload-artifact@v4
        with:
          name: mapping
          path: ${{ env.FGA_MAPPING_PATH }}

  release:
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Tag Version
        run: |
          echo "VERSION_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        uses: actions/github-script@v6
        with:
          script: |
            const run_tag = `${{ github.run_number }}`; 
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${run_tag}`,
              sha: context.sha
            })
      - uses: actions/download-artifact@v4
        with:
          name: apk

      - name: Rename apk
        run: mv app-preview.apk fga-preview-${{ env.VERSION_TAG }}.apk

      - name: Zipped APK
        run: zip -r fga-preview-${{ env.VERSION_TAG }}.zip fga-preview-${{ env.VERSION_TAG }}.apk

      - name: Create tagged Release
        uses: ncipollo/release-action@v1.13.0
        with:
          generateReleaseNotes: true
          artifacts: fga-preview-${{ env.VERSION_TAG }}.zip
          tag: ${{ env.VERSION_TAG }}
          name: 'FGA Preview ${{ github.run_number }}'
          prerelease: false
